databases:
  - name: nexus-chat-db
    plan: free
    databaseName: nexus_chat
    user: nexus_user

services:
  - type: web
    name: nexus-chat-web
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT nexus_chat.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nexus_chat.settings.prod
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: nexus-chat-db
          property: connectionString
